---
title: "WSTC3 Abstracts"
author: "World Seabird Union"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)

X <- tbl_df(read.csv('AbstractsV2.csv'))

Y <- select(X, First, Last, Email, Handle, Country, Affiliation, Title, Abstract)

```

```{r echo=FALSE, results='asis'}


for(x in 1:nrow(Y)){
  
  cat('##',as.character(Y$First[x]),as.character(Y$Last[x]),' \n')
  cat('<table>')
  cat('<tr >')
  cat('<td>HANDLE: ',as.character(Y$Handle[x]),'</td>')
  cat('<td>COUNTRY: ',as.character(Y$Country[x]),'</td>')
  cat('<td>AFFILIATION: ',as.character(Y$Affiliation[x]),'</td>')
  cat('<td>E-MAIL: ',as.character(Y$Email[x]),'</td>')
  cat('TITLE: ')
  cat('*',as.character(Y$Title[x]),'*','  \n',sep='')
  cat('<tr style="border-style:solid; border-bottom-color: #000;border-top-color: #fff; border-left-color:#fff;border-right-color:#ffff; border-width: 1px;" ><td style="padding-bottom:20px;" colspan=5>ABSTRACT: ',as.character(Y$Abstract[x]),'</td></tr>')
  cat('</tr>')
  cat('</table>','  \n')
  
  cat("----------------------------------------------------------------------------------   \n")
}



```